[package]
authors = ["nomaterials <nomaterials@gmail.com>"]
edition = "2021"
name = "rust-nix-template"
description = "A Rust project"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
